
const ACTIONTYPES = {
     ADD : "ADD",
     REDUCE : "REDUCE",
     FETCH_RESTAURANT_REQUEST : "FETCH_RESTAURANT_REQUEST",
     FETCH_RESTAURANT_SUCCESS : "FETCH_RESTAURANT_SUCCESS",
     FETCH_RESTAURANT_FAILURE : "FETCH_RESTAURANT_FAILURE",
     UPDATE_ONLY_VEG_PREFERENCE : "UPDATE_ONLY_VEG_PREFERENCE",
}
export default ACTIONTYPES;