
const ActionTypes = {
     ADD : "ADD",
     REDUCE : "REDUCE",
     FETCH_MENU_REQUEST : "FETCH_MENU_REQUEST",
     FETCH_MENU_SUCCESS : "FETCH_MENU_SUCCESS",
     FETCH_MENU_FAILURE : "FETCH_MENU_FAILURE",
     UPDATE_ONLY_VEG_PREFERENCE : "UPDATE_ONLY_VEG_PREFERENCE",
}
export default ActionTypes;